# Lesson 1: First glance at Jupyter.
## Second level of title: Markdown grammar.
### Third level of title.

* First, enter ESC, then inter m, the cell is changed to markdown.
* Then, one can take notes.
* One can even input formula e.g. $e^{i\boldsymbol{k}\cdot\boldsymbol{r}}$.

$\int e^{i\hat{H}t/\hbar} \, {\rm{d}} x$

$$\begin{aligned} \int D(x) e^{iS} \end{aligned}$$



## Example

$\hat{L} \rho = [H, \rho]$


# "*In mathematics, you never understand things; you just get used to them.*" --John von Neumann

In [4]:
print("Hello world!")
print("Hello again!")
print("Who am I")
print("Version of Python")


Hello world!
Hello again!
Who am I
Version of Python


# Markdown cheat sheet:

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet


# Mastering Markdown:

https://guides.github.com/features/mastering-markdown/


## Basic usage of Python Jupyter：

1. Normal：Input mode。
2. Esc: Command-line mode。
3. Esc+y: coding mode。
4. Esc+m: Markdown mode。
5. Esc+l: Line number。
6. Shift+Enter: Run!
7. Esc+b: Start a new cell bellow。
8. Esc+a: Start a new cell above。

## Two modes：

Command mode and Edit mode. In a cell，press Enter, one can get into the *Edit* mode. If press Esc, one can get into the *Command* mode.

## Run current cell，and then move to the next Cell

在一个cell中（在command模式下）,  Shift + Enter  

## Create a Cell

Within a cell（in command mode）
1. Press a, a new cell appears above；
2. Press b, a new cell appears bellow;

## Code/Markdown mode switching

Within a cell (in command mode)
1. Press y, Code mode;
2. Press m, Markdown mode;

## Delete a Cell

Within a cell（in command mode）, press d twice 
**DANGER**! 


## Save current Notebook

Within a cell (in command mode), press s.


## Start a command panel (not useful in Mac)

Within a cell (in command mode), Press: 
```Python
Ctrl + Shift + P 
```




# A table: 

Alice|Bob|Charlie
--|:--:|--:
B|A|C
C|B|A
A|C|B

In [6]:
1234+5678

6912

In [7]:
1234*5678

7006652

In [8]:
1234/5678

0.2173300457907714

In [10]:
print("%12.6f\n" % 5.6)

    5.600000



In [12]:
import numpy as np

a = np.ones(3)
print("a:",a)
s = ''
for i in range(len(a)):
    print("i: ",i)
    s += '{:12.6f}'.format(a[i])
print(s)

a: [1. 1. 1.]
i:  0
i:  1
i:  2
    1.000000    1.000000    1.000000


In [13]:
print(np.__version__)

1.17.4


In [14]:
1234/5678

0.2173300457907714

In [15]:
int(int(1234)/int(5678))

0

In [20]:
int(np.ceil(int(1234)/int(5678)))

1

In [21]:
int(np.floor(3/4))

0

In [27]:
import numpy as np
a = np.linspace(1,10,91)
print (a)
print(len(a))

[ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3
  2.4  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7
  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1
  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5
  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9
  8.   8.1  8.2  8.3  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3
  9.4  9.5  9.6  9.7  9.8  9.9 10. ]
91


In [26]:
b = np.arange(1,10+0.1,0.1)
#b = np.arange(1,10,0.1)
print(b)
print(len(b)) ## len: length of an array.

[ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3
  2.4  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7
  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1
  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5
  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9
  8.   8.1  8.2  8.3  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3
  9.4  9.5  9.6  9.7  9.8  9.9 10. ]
91


In [29]:
x = [1.0,2.0,3.0]
print(type(x))

<class 'list'>


In [31]:
print(x)

[1.0, 2.0, 3.0]


In [30]:
print(a)

[ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3
  2.4  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7
  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1
  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5
  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9
  8.   8.1  8.2  8.3  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3
  9.4  9.5  9.6  9.7  9.8  9.9 10. ]


In [32]:
print(type(a))
print(type(b))
print(np.shape(a))
c=np.matrix(a,dtype=float)
print(type(c))
print(np.shape(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(91,)
<class 'numpy.matrix'>
(1, 91)


In [33]:
print(c[0,0])

1.0


```bash
conda install keras 
```

# Python for windows: Anaconda 
## Anaconda: 
## https://www.anaconda.com
## ![conda](https://binstar-static-prod.s3.amazonaws.com/latest/img/AnacondaCloud_logo_V_green.png)

# Modules: 
## Jupyter: conda install jupyter
## Matplotlib
## numpy
## pandas
## numba
## SciPy

Pearl

In [4]:
import math
print math.sqrt(2)
print np.sqrt(2)

1.41421356237
1.41421356237


In [ ]:
from math import sqrt
sqrt(3)

## Variables in Python：

* Initiate of a character or '_'，followed by character、number、'_'。**DONOT INITIATE AS NUMBER!。
* Case sensive！Donot add blank.
* Format: 
```Python
< Name > = < value >
```
* Continue sign: \


In [35]:
_30 = 30

In [36]:
a = 2
print (a)

b = a

c = a + \
b

print("b: ", b)
print("c: ", c)
print(id(a))
print(id(b))
print(id(c))
b = 2
print(id(b))

2
b:  2
c:  4
4418491840
4418491840
4418491904
4418491840


In [21]:
d= a
print(id(d))
e = b
print(id(e))


4548298176
4548298176


In [23]:
a = 3
print(a, b, d, e)
print(id(a),id(b),id(d),id(e))

3 2 2 2
4548298208 4548298176 4548298176 4548298176


In [24]:
import copy ## Recommended method of assigning an array to another variable!
f = copy.deepcopy(e)
print(id(f))
e = 4
print(a, b, d, e, f)

4548298176
3 2 2 4 2


Specified **module** for special usages：

```Python
import math
```

* `x**2`: Calculate $x^2$. If x is a matrix，return each element's square in $x$。
* `inf`: Positive infinity
* `and`, `or`, `not`: logical operator
* ```Python
a = {'k':'d','l':'o'}
a.get('a','z')
```

Here `get` is equal to an `if`. If the former value（called “key”）is in `a`, Then return the corresponding value（called “value”), or else return the latter one. 

* `type(a)`: returns the type of `a`.
* `z = complex(x,y)`: Defines a complex number: $z=x+iy$. (the module `numpy` is needed)
`real(z)` for the real part, `imag(z)`for its imaginary part, and `abs(z)` for its module. 


In [37]:
x = 4
y = 1.5
print(x**y)

8.0


In [38]:
a = {'k':'d','l':'o'}
a.get('k','z')

'd'

In [39]:
a.get('k','z')

'd'

In [40]:
import numpy as np
z = complex(2.0,4.0)
print(z)
print(np.real(z))
print(np.imag(z))
print(np.abs(z))
print(np.sqrt(2.0**2+4.0**2))

(2+4j)
2.0
4.0
4.47213595499958
4.47213595499958


### Excersize：
1. The value of $\log(29)$ and value of $e$.
2. For the value of a function:
$$\begin{aligned}
f(x) = \displaystyle\frac{x^3-2e^{-x}+6.3}{\sqrt{x^2+\pi^2}\ln{(x+0.5)}}
\end{aligned}$$
$f(2) = ?$


In [41]:
## Answer：

print(np.log(29.0))
print(np.e)
print(np.pi)

def ff(x):
    y = (x**3 - 2*np.e**(-x)+6.3)\
    /(np.sqrt(x**2+np.pi**2)*np.log(x+0.5))
    return y

print("ff(2.0) is: ",ff(2.0))

3.367295829986474
2.718281828459045
3.141592653589793
ff(2.0) is:  4.111228190084167


## Basic operations of matrices

1. 
```Python
a = [1, 2, 3]
```

In [42]:
a = [1, 2, 3] ## midlle bracket！！！
print(a)

[1, 2, 3]


In [43]:
print (type(a))

<class 'list'>


In [44]:
a = np.array(a)
print(type(a))

<class 'numpy.ndarray'>


In [45]:
print(a)

[1 2 3]


In [46]:
b = tuple(a)
print (b)
print (type(b))

(1, 2, 3)
<class 'tuple'>


In [47]:
a[2]=12
print(a)

[ 1  2 12]


In [48]:
b[2]=15
print(b)


TypeError: 'tuple' object does not support item assignment

In [49]:
print(b[2])

3


In [51]:
c = [[1,3],[4,5]]
print(c)
print(c[0][1])
print(type(c))

[[1, 3], [4, 5]]
3
<class 'list'>


In [53]:
import numpy as np
x = np.zeros((3,3))
x[0,1]=3
print(x)
print(type(x))

[[0. 3. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [20]:
print type(c)
print type(x)

<type 'list'>
<type 'numpy.ndarray'>


## Get part of the matrix：comma (":")

In [55]:
import numpy as np
a = np.zeros((3,3));
print(a)
for i in range(3):
    for j in range(3):
        a[i,j] = i+j

print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]


* `A[:,k]`   The $k$th column of $A$
* `A[k,:]`   The $k$th row of $A$
* `A[:,k:m]`   The sub-matrix composed by the $k$th to ($m-1$)th row of $A$.


In [57]:
a[0:2,0:2]

array([[0., 1.],
       [1., 2.]])

# Excersize：
Define an arbitary $4\times 4$ matrix，then get a sub matrix composed by the 1, 3 row and 1, 2 column of $A$ (a $2\times 2$ matrix).

In [58]:
print(a>3)

[[False False False]
 [False False False]
 [False False  True]]


In [60]:
print(a[a>3])


[4.]


In [61]:
print(a[a<3])

[0. 1. 2. 1. 2. 2.]


Comon matrix functions：
```Python
np.zeros()
np.ones()
np.diag()
np.random.rand()
np.random.randn()
```
HW: What's the different between rand and randn?

In [66]:
print(np.diag((3,3,5)))

[[3 0 0]
 [0 3 0]
 [0 0 5]]


In [29]:
print np.random.rand(3,3)

[[ 0.02168266  0.66371713  0.04221692]
 [ 0.89340548  0.05496524  0.06364989]
 [ 0.96632395  0.79121522  0.89133716]]


In [68]:
print(np.diag(a))

[0. 2. 4.]


Check the size of a matrix：

```Python
np.size()
np.length()
```
Check the shape of a matrix:
```Python
np.shape()
```

In [73]:
print(np.size(a))
#print(np.length(a))
print(np.shape(a))

9
(3, 3)


# Matrix operation

```Python
np.concatenate()
np.vstack()
np.hstack()
```
* Product element by element: 
```Python
A*B
```
or
```Python
np.multiply(A,B)
```
* dot prouct: 
```Python
np.dot(A,B)
```
* Inverse:
```Python
np.linalg.inv(A)
```

```Python
A = np.matrix(A)
A.I
```

In [74]:
a = np.zeros((3,3))
print(a)
print(np.size(a))
print(np.shape(a))
m, n = np.shape(a) ###
print(m, n)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
9
(3, 3)
3 3


In [20]:
b = np.ones((3,3))
print(b)
c = np.vstack((a,b))
print(c)
d = np.hstack((a,b))
print("d:")
print(d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
d:
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [75]:
A = np.random.normal(1.0,2.0,(3,3))
B = np.random.random((3,3))
print(A)
print("---")
print(B)
print("---")
print(A*B)


[[1.04441065 3.87894104 0.53566449]
 [2.43011349 1.382988   0.97802174]
 [2.07884003 3.79777179 1.00297903]]
---
[[0.09464005 0.29568651 0.89857288]
 [0.43805958 0.53838293 0.36858571]
 [0.43027705 0.54233443 0.68402568]]
---
[[0.09884308 1.14695052 0.48133358]
 [1.06453449 0.74457713 0.36048484]
 [0.89447716 2.0596624  0.68606341]]


In [76]:
print(A[0,1]*B[0,1])

1.146950522436421


In [77]:
print(np.multiply(A,B))

[[0.09884308 1.14695052 0.48133358]
 [1.06453449 0.74457713 0.36048484]
 [0.89447716 2.0596624  0.68606341]]


In [79]:
print(np.dot(A,B))

[[2.0285345  2.68768307 2.73460959]
 [1.25663752 1.99354376 3.36237567]
 [2.2919507  3.2032905  3.9538571 ]]


In [80]:
b = np.zeros((2,2))
b[0,0]=1.0
b[1,1] = -b[0,0]
b[0,1] = 0.4
b[1,0] = 0.5
print(b)
print(type(b))
print(np.linalg.inv(b))

c = np.mat(b)
print(c.I)
print(type(c))

[[ 1.   0.4]
 [ 0.5 -1. ]]
<class 'numpy.ndarray'>
[[ 0.83333333  0.33333333]
 [ 0.41666667 -0.83333333]]
[[ 0.83333333  0.33333333]
 [ 0.41666667 -0.83333333]]
<class 'numpy.matrix'>


## Operation for Matrices：
* .T －－ return the **t**ranspose

* .H －－ return the **H**ermite conjugation

* .I －－ return the **i**nverse

In [33]:
print c.T

[[ 1.   0.5]
 [ 0.4 -1. ]]


# The strings in Python

Hello world!

In [81]:
print('Hello world!')

Hello world!


In [82]:
a=3.0
b=2.0
print(a+b)


5.0


In [83]:
ca = "2.0"
cb = "3.0"
print(ca+cb)

2.03.0


In [84]:
p="Plato"


In [85]:
p[1]

'l'

In [86]:
p[-1]

'o'

In [87]:
len(p)

5

In [ ]:
p[len(p)-2] # also works, but why write len(p) all the time?

In [35]:
p[0:1]

'P'

In [88]:
p[2:4]

'at'

```python
(stop - start) == len(s[start:stop])
```

![String](./graph/string.png)

In [ ]:
p[1:-1]

In [ ]:
p[-1:2]

In [ ]:
print p[:2] # the first two elements 
print p[-2:] # the last five elements 
print p[:] # the whole string!
print p[:-1]

In [36]:
#q = "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz"
q = "AaBbCc"

```python
s[start:stop:step]
```

In [ ]:
q[2:-2:2]

In [ ]:
q[1::2]

In [37]:
q[::-3] ## ?????

'cB'

In [ ]:
              1
#   01234567890123456
x = "neveroddoreven" ## Clue here.
x == x[::-1]

To create a raw slice, use the expression 
```python
slice(start, stop, step). 
```

In [ ]:
q =p[slice(1,3,1)]
print q

In [ ]:
my_slice = slice(3, 1415, 9) # my slice of the pi

In [ ]:
my_slice = slice(3,10, 9) # my slice of the pi

In [ ]:
print x[my_slice]
print len(x)

## String Concatenation

In [ ]:
print "kilo" + "meter"

In [89]:
print("x^" + str(2))

x^2


$x^2$


In [90]:
print("x^"+'{:08d}'.format(3))

x^00000003


In [92]:
print("x^"+'{:08.2f}'.format(2.0))

x^00002.00


In [93]:
"newto" * 10

'newtonewtonewtonewtonewtonewtonewtonewtonewtonewto'

In [94]:
Quote="Bones said, \"He\'s dead, Jim.\""

In [96]:
print(Quote)

Bones said, "He's dead, Jim."



Character | Interpretation 
:--: | --: 
 \\\ | Backslash 
 \n | Newline—start a new line 
 \r | Carriage return - go to the start of this line 
 \t | Tab 
 \' | Single quote 
 \" | Double quote 



## String methods

In [98]:
header = " temperature pressure\t value \n"

In [99]:
print(header)

 temperature pressure	 value 



In [100]:
header.strip()

'temperature pressure\t value'

In [101]:
print(header.strip())

temperature pressure	 value


In [102]:
print(header.upper())

 TEMPERATURE PRESSURE	 VALUE 



If $n\in \mathbb{N}$, the `"n".isdigit()` is `True`.

In [103]:
"10".isdigit() ## True once "n" is integer.

True

In [104]:
"10.10".isdigit()

False

In [105]:
hL=header.upper()
print(hL.swapcase())

 temperature pressure	 value 



In [106]:
print('Plato'.swapcase())

pLATO


## More complecated

In [107]:
"{0} gets into work & then his {1} begins!"\
.format("Hilbert", "commute")

'Hilbert gets into work & then his commute begins!'

In [ ]:
'{:12f}'.format(1.0E4)

In [ ]:
help(len)

In [ ]:
x=42
y=65.0
print "Formatted: x={0} y={1}".format(x, y)
print "x=" + str(x) + " y=" + str(y)


## Libraries -- modules


Module | Description
 :-   |  :-
os   | Operating system abstractions: file path operations, file removal, etc. 
sys  | System-specific, gets into the guts of the Python interpreter
math | Everyday mathematical functions and constants
re   | Regular expression library
subprocess | Spawns child processes and shells, good for running other command-line tools 
argparse   | Creates easy and beautiful command-line utilities
itertools  | Helpful tools for looping
collections | Advanced collection types and tools for making custom collections
decimal    | Arbitrary-precision integers and floats
random     | Pseudo-random number generators
csv        | Tools for reading and writing comma-separated value files
pdb        | The Python debugger (similar togdbfor C/C++/Fortran) logging Utilities for logging the progress of a program while it is running

# Elementary coding

1. if
2. for loop
3. print
4. debug

In [109]:
a = input("Show me the a:\n") ## Now a is a string.
a = float(a)

if a>5 or a<0:
    print(a)
else:
    print("I don't want to print.")
    
    

Show me the a:
10
10.0


In [112]:

for i in range(5):
    if i>2:
        print(i)
        
x=[11.0,21.0,33.0,44.0]
for xi in x:
    print("Before: ", xi)
    if xi>30.0:
        break
    print("After: ", xi)

3
4
Before:  11.0
After:  11.0
Before:  21.0
After:  21.0
Before:  33.0


# Excersize:

Generate a random integer within [1,20]，then guess this number。
Give hints for missed guess:
* “High”, too large. 
* “Low” , too small. 
* Gets hitted, show “You won", and then quit the program. 
* One has as much as 7 tries.


In [3]:

import numpy as np

a = 0.0
a = np.random.rand()
eps = 1.0E-6
for i in range(7):
    
    b = input("Give me a guess:")
    b = np.float(b)
    c = (b-a)
    if np.abs(c)< eps:
        print("You won!")
        break
    elif c>0:
        print("High")
    elif c<0:
        print("Low")



Give me a guess:3
High
Give me a guess:3
High
Give me a guess:1
High
Give me a guess:2
High
Give me a guess:5
High
Give me a guess:-1
Low
Give me a guess:0
Low


In [3]:
43*0.7+30

60.099999999999994